name = "miniorg-www"
account_id = "3676fa8d525890e7ddf8e55650e6c144"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"

[vars]
NODE_ENV = "production"
